version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}  # Use MongoDB Atlas connection string from .env
    volumes:
      - ./uploads:/app/uploads   # Syncs uploads folder between host and container
    env_file:
      - .env  # Load environment variables from .env file
    command: npm start  # Command to start the app
